GET http://localhost:3000/booking

###

POST http://localhost:3000/booking
Content-Type: application/json

{
    "category_id": "1",
    "firstname": "Marcus",
    "lastname": "Eriksen",
    "email": "mke@mke.dk",
    "phonenumber": "22334455",
    "height": "1.80",
    "weight": "70",
    "seize": "48",
    "status": "0",
    "created_at": "22/01/2022"
}

###

GET http://localhost:3000/bookingcategory

###

POST http://localhost:3000/bookingcategory
Content-Type: application/json

{
    "title": "Open Water Referral",
    "description": "Referral kurser afholdes Mandag til onsdag ",
    "position": "",
    "adress": "",
    "time": "Mandag kl. 17-21",
    "price": "1.995,00",
    "amount": "2",
    "max_amount": "10",
    "place": "Greve - Mosede Havn",
    "type": "Båd",
    "depth": "0-6 meter",
    "img": "img1.png"
}
